// Generated by CoffeeScript 1.10.0
(function() {
  var Queue;

  Queue = (function() {
    function Queue(initialArray) {
      if (initialArray == null) {
        initialArray = [];
      }

      /*
      Pass an optional array to be transformed into a queue. The item at index 0
      is the first to be dequeued.
       */
      this._values = initialArray;
      this._index = 0;
      this.size = this._values.length;
    }

    Queue.prototype.push = function(item) {

      /*
      _Returns:_ the item.
       */
      this.size++;
      this._values.push(item);
      return item;
    };

    Queue.prototype.pop = function() {

      /*
      _Returns:_ the dequeued item.
       */
      var itemToDequeue;
      if (this.size === 0) {
        return;
      }
      this.size--;
      itemToDequeue = this._values[this._index];
      this._index++;
      if (this._index * 2 > this._values.length) {
        this._values = this._values.slice(this._index);
        this._index = 0;
      }
      return itemToDequeue;
    };

    Queue.prototype.peek = function() {

      /*
      Check the next item to be dequeued, without removing it.
      _Returns:_ the item.
       */
      return this._values[this._index];
    };

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
